version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - ammojs
  - antfu
  - Blinn
  - BPPV
  - BRDF
  - CCDIK
  - Clearcoat
  - envmap
  - Eulers
  - glsl
  - gradientmap
  - irradiances
  - matcap
  - Metcap
  - moeru
  - noname
  - Phong
  - pkgroll
  - PVRTC
  - slerp
  - sonarjs
  - threejs
  - Toon
ignoreWords: []
import: []
