packages:
  - docs
  - examples/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^5.2.1
  '@eslint-react/eslint-plugin': ^1.52.3
  '@moeru/eslint-config': 0.1.0-beta.7
  '@moeru/tsconfig': 0.1.0-beta.7
  '@noname0310/mmd-parser': ^0.1.4
  '@types/three': ^0.179.0
  ammojs-typed: ^1.0.6
  eslint: ^9.33.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  pkgroll: ^2.15.3
  three: ^0.179.1
