packages:
  - docs
  - examples/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^5.4.1
  '@eslint-react/eslint-plugin': ^2.0.1
  '@moeru/eslint-config': ^0.1.0-beta.10
  '@moeru/tsconfig': ^0.1.0-beta.10
  '@noname0310/mmd-parser': ^0.1.6
  '@types/three': ^0.180.0
  '@vitejs/plugin-react': ^5.0.3
  ammojs-typed: ^1.0.6
  babylon-mmd: ^0.68.0
  bumpp: ^10.2.3
  eslint: ^9.36.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.22
  pkgroll: ^2.15.4
  three: ^0.180.0
  typescript: ~5.9.2
  vite: ^7.1.7

catalogs:
  r3f:
    '@generouted/react-router': ^1.20.0
    '@react-three/drei': ^10.7.6
    '@react-three/fiber': ^9.3.0
    '@types/react': ^19.1.14
    '@types/react-dom': ^19.1.9
    react: ^19.1.1
    react-dom: ^19.1.1
    react-router: ^7.9.3
    suspend-react: ^0.1.3

onlyBuiltDependencies:
  - esbuild
