packages:
  - docs
  - examples/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^5.2.1
  '@eslint-react/eslint-plugin': ^1.52.3
  '@moeru/eslint-config': ^0.1.0-beta.8
  '@moeru/tsconfig': ^0.1.0-beta.8
  '@noname0310/mmd-parser': ^0.1.4
  '@types/three': ^0.179.0
  '@vitejs/plugin-react': ^5.0.1
  ammojs-typed: ^1.0.6
  bumpp: ^10.2.3
  eslint: ^9.33.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  mmd-parser: ^1.0.4
  pkgroll: ^2.15.3
  three: ^0.179.1
  typescript: ~5.8.3
  vite: ^7.1.3

catalogs:
  r3f:
    '@generouted/react-router': ^1.20.0
    '@react-three/drei': ^10.7.4
    '@react-three/fiber': ^9.3.0
    '@types/react': ^19.1.11
    '@types/react-dom': ^19.1.7
    react: ^19.1.1
    react-dom: ^19.1.1
    react-router: ^7.8.2

onlyBuiltDependencies:
  - esbuild
